name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: test
        run: npm test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
