name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
      - run: npm ci
      - name: test
        run: npm test
